-- Admin analytics: daily participation, bounded writes, and backend-only access.
-- Scaffold generated by the CLI; ordered after the existing Prisma ledger.
SET lock_timeout = '5s';
CREATE TABLE learning_activity_days (
  student_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
  course_id UUID NOT NULL REFERENCES courses(id) ON DELETE CASCADE ON UPDATE CASCADE,
  day DATE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC')::date,
  recorded_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (student_id, course_id, day)
);
CREATE INDEX learning_activity_days_course_day_idx ON learning_activity_days(course_id, day);
CREATE INDEX learning_activity_days_day_idx ON learning_activity_days(day);
CREATE TABLE learning_activity_coverage (
  id INTEGER PRIMARY KEY DEFAULT 1 CHECK (id = 1),
  started_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE learning_activity_days ENABLE ROW LEVEL SECURITY;
ALTER TABLE learning_activity_coverage ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON learning_activity_days, learning_activity_coverage FROM PUBLIC, anon, authenticated, nce_app_anon;
GRANT SELECT, INSERT ON learning_activity_days, learning_activity_coverage TO nce_app_authenticated;
GRANT SELECT, INSERT, DELETE ON learning_activity_days, learning_activity_coverage TO service_role;
CREATE POLICY activity_read ON learning_activity_days FOR SELECT TO nce_app_authenticated
  USING (current_setting('app.current_user_role', true) = 'admin'
    OR student_id::text = current_setting('app.current_user_id', true));
CREATE POLICY activity_write ON learning_activity_days FOR INSERT TO nce_app_authenticated
  WITH CHECK (current_setting('app.current_user_role', true) = 'student'
    AND student_id::text = current_setting('app.current_user_id', true)
    AND day = (CURRENT_TIMESTAMP AT TIME ZONE 'UTC')::date
    AND recorded_at = CURRENT_TIMESTAMP);
CREATE POLICY coverage_read ON learning_activity_coverage FOR SELECT TO nce_app_authenticated USING (true);
CREATE POLICY coverage_write ON learning_activity_coverage FOR INSERT TO nce_app_authenticated
  WITH CHECK (id = 1 AND started_at = CURRENT_TIMESTAMP);

-- Store only one participation fact per learner/course/UTC day, never answers or view counts.
-- Successful learning mutations participate in the same transaction as their daily fact.
CREATE FUNCTION record_learning_write() RETURNS trigger LANGUAGE plpgsql SECURITY INVOKER
SET search_path = public, pg_temp AS $$
DECLARE target_course UUID; target_student UUID;
BEGIN
  IF TG_TABLE_NAME = 'submissions' THEN
    SELECT course_id INTO target_course FROM assignments WHERE id = NEW.assignment_id AND "deletedAt" IS NULL;
    target_student := NEW.student_id;
    IF NEW."deletedAt" IS NOT NULL OR (TG_OP = 'UPDATE' AND NEW.payload IS NOT DISTINCT FROM OLD.payload
      AND NEW.submitted_at IS NOT DISTINCT FROM OLD.submitted_at) THEN RETURN NEW; END IF;
  ELSE
    target_course := NEW.course_id; target_student := NEW.student_id;
  END IF;
  -- Grading, imports, background jobs and administrative writes are not student participation.
  IF current_setting('app.current_user_role', true) <> 'student'
    OR current_setting('app.current_user_id', true) IS DISTINCT FROM target_student::text THEN RETURN NEW; END IF;
  INSERT INTO learning_activity_days(student_id, course_id)
    SELECT target_student, target_course WHERE EXISTS (
      SELECT 1 FROM enrollments e JOIN users u ON u.id = e.user_id JOIN courses c ON c.id = e.course_id
      WHERE e.user_id = target_student AND e.course_id = target_course AND e.role_in_course = 'student'
        AND e."deletedAt" IS NULL AND u."deletedAt" IS NULL AND u.role = 'student' AND u.status = 'active'
        AND c."deletedAt" IS NULL)
    ON CONFLICT DO NOTHING;
  RETURN NEW;
END $$;
REVOKE ALL ON FUNCTION record_learning_write() FROM PUBLIC, anon, authenticated;
CREATE TRIGGER submissions_learning_activity AFTER INSERT OR UPDATE ON submissions FOR EACH ROW EXECUTE FUNCTION record_learning_write();
CREATE TRIGGER attempts_learning_activity AFTER INSERT OR UPDATE ON nce_exercise_attempts FOR EACH ROW EXECUTE FUNCTION record_learning_write();
CREATE TRIGGER completion_learning_activity AFTER INSERT OR UPDATE ON nce_lesson_progress FOR EACH ROW EXECUTE FUNCTION record_learning_write();

CREATE FUNCTION start_learning_coverage() RETURNS trigger LANGUAGE plpgsql SECURITY INVOKER
SET search_path = public, pg_temp AS $$
BEGIN
  INSERT INTO learning_activity_coverage(id) VALUES (1) ON CONFLICT DO NOTHING;
  RETURN NEW;
END $$;
REVOKE ALL ON FUNCTION start_learning_coverage() FROM PUBLIC, anon, authenticated;
CREATE TRIGGER learning_coverage_start AFTER INSERT ON learning_activity_days FOR EACH ROW EXECUTE FUNCTION start_learning_coverage();

INSERT INTO navigation_items(role, label, path, icon_name, required_permission, order_index, is_active)
SELECT 'admin', 'Analytics', '/admin/analytics', 'bar-chart-3', 'analytics:view', 8, true
WHERE NOT EXISTS (SELECT 1 FROM navigation_items WHERE role = 'admin' AND path = '/admin/analytics');
